version: 2.1
jobs:
  build:
    docker:
    - image: cimg/node:12.16
    steps:
    - checkout
    - run:
        command: |
          npm ci
          npm run build --if-present
  generate_calendar_image:
    docker:
    - image: cimg/node:21.0
    steps:
    - checkout
    - run:
        name: Install dependencies
        command: |
          rm -rf node_modules
          npm install canvas fs dayjs
    - run:
        name: image generate and commit
        command: |
          git lfs install
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          node dark.js
          node white.js
          rm -f dark.png
          rm -f white.png
          git add .
          git commit -m "del old-generate"
          git push -f -u origin main
          cd ..
          cp -f dark.png ./Calendar-rate
          cp -f white.png ./Calendar-rate
          rm -rf ./Calendar-rate/.git
          mv Calendar-rate subfolder_tmp
          git submodule deinit Calendar-rate
          git rm --cached Calendar-rate
          mv subfolder_tmp Calendar-rate
          git add Calendar-rate
          cd Calendar-rate
          git add .
          git commit -m "generate"
          git push -f -u origin main
workflows:
  Node.js_CI_and_Calendar_Image_Generation:
    jobs:
    - build:
        filters:
          branches:
            only:
            - main
          tags: {}
    - generate_calendar_image:
        filters:
          branches:
            only:
            - main
          tags: {}
# Translated via CircleCI's Configuration Translator
# Info :: Could not translate "workflow_dispatch" trigger event to an equivalent in CircleCI's config.yml.  To run a pipeline manually from the CircleCI UI, see the following documentation: https://circleci.com/docs/triggers-overview/#run-a-pipeline-from-the-circleci-web-app.  To run a pipeline using the CircleCI API, see the following documentation: https://circleci.com/docs/triggers-overview/#run-a-pipeline-using-the-api
# Info :: Could not translate "pull_request" trigger event to an equivalent in CircleCI's config.yml
# Info :: Could not translate "schedule" trigger event to an equivalent in CircleCI's config.yml.  To schedule a pipeline, see the following documentation https://circleci.com/docs/scheduled-pipelines/
