name: Node.js CI and Calendar Image Generation

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '*/5 * * * *' # Run every minute

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present

  generate_calendar_image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install canvas fs dayjs

      - name: image generate and commit
        run: |
          git config --global user.email "action@github.com"
          git clone https://github.com/0x-sinsu/Calendar-rate.git
          node dark.js
          node white.js
          git config --global user.name  "actions-user"
          rm -f ./Calendar-rate/dark.png
          rm -f ./Calendar-rate/white.png
          git add .
          git commit -m 'del old-generate'
          git remote rm origin
          git remote add origin https://0x-sinsu:${{ secrets.GH_ACCESS_TOKEN }}@github.com/0x-sinsu/Calendar-rate.git
          git push -u origin main
          cp -f dark.png ./Calendar-rate
          cp -f white.png ./Calendar-rate
          cd Calendar-rate
          git add .
          git commit -m 'generate'
          git remote rm origin
          git remote add origin https://0x-sinsu:${{ secrets.GH_ACCESS_TOKEN }}@github.com/0x-sinsu/Calendar-rate.git
          git push -u origin main
