name: Node.js CI and Calendar Image Generation

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '*/5 * * * *' # Run every minute

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [21.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present

  generate_calendar_image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21'

      

      - name: Install dependencies
        run: |
          rm -rf node_modules
          npm install canvas fs dayjs

      - name: image generate and commit
        run: |
          git lfs install
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          node dark.js
          node white.js
          rm -f dark.png
          rm -f white.png
          git add .
          git commit -m 'del old-generate'
          git push -f -u origin main
          cd ..
          cp -f dark.png ./Calendar-rate
          cp -f white.png ./Calendar-rate
          rm -rf ./Calendar-rate/.git
          mv Calendar-rate subfolder_tmp
          git submodule deinit Calendar-rate
          git rm --cached Calendar-rate
          mv subfolder_tmp Calendar-rate
          git add Calendar-rate
          cd Calendar-rate
          git add .
          git commit -m 'generate'
          git push -f -u origin main
